# CodifyDB  Development Container

version: '3.1'
services:
  grafana:
    image: grafana/grafana:5.1.0
    ports:
      - 3000:3000
    user: 'grafana'
  db:
    image: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=codify
      - APP_DB_PASS=codify_2021
      - APP_DB_NAME=codifydb
    volumes:
      - ./postgresdb:/docker-entrypoint-initdb.d/
      - ./:/code/
    ports:
      - "5432:5432"
      
  os:
    image: ubuntu
    restart: always
    build: ./ubuntu
    volumes:
      - ./:/python/    
    
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  static:
  media:
