# Generated by Django 3.2.9 on 2021-11-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor', models.TextField()),
                ('frequency', models.TextField()),
                ('check_type', models.TextField()),
                ('description', models.TextField()),
                ('check_command', models.TextField()),
                ('result_column', models.TextField()),
                ('priority', models.IntegerField()),
                ('handler', models.TextField()),
            ],
            options={
                'db_table': 'checklist',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_tier', models.TextField()),
            ],
            options={
                'db_table': 'targets',
            },
        ),
    ]
