# Generated by Django 3.2.9 on 2021-11-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='support_tier',
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
