# Generated by Django 3.2.9 on 2021-11-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0002_auto_20211117_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='inventory_create',
            field=models.DateField(default='2021-11-17'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
