# Generated by Django 3.2.9 on 2021-11-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0003_auto_20211117_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='target',
            name='inventory_create',
        ),
        migrations.AddField(
            model_name='target',
            name='support_tier',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='check_command',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='check_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='handler',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='result_column',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='vendor',
            field=models.TextField(blank=True),
        ),
    ]
