# Generated by Django 3.2.9 on 2021-11-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0004_auto_20211117_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='archivelog_mode',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='blocksize',
            field=models.IntegerField(blank=True, default=8192),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='container',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='database_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='db_created_date',
            field=models.DateField(blank=True, default='2021-11-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='decommissioned',
            field=models.DateField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='highlysensitiveinfo',
            field=models.BinaryField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='home_dir',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='host_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='hostname',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='important_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='instance_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='inventory_create',
            field=models.DateField(blank=True, default='2021-11-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='last_check_date',
            field=models.DateTimeField(blank=True, default='2021-11-17'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='os',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='owner',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='port',
            field=models.IntegerField(blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='target',
            name='role',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='serial_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='standby_dest',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='target_type',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='v_instance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='vendor',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='target',
            name='version',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
