# Generated by Django 3.2.9 on 2021-11-17 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0005_auto_20211117_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='id',
            new_name='inventory_id',
        ),
    ]
