# Generated by Django 3.2.9 on 2021-11-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0006_rename_id_target_inventory_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='clustered',
            field=models.TextField(blank=True),
        ),
    ]
