# Generated by Django 3.2.9 on 2021-11-18 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0007_target_clustered'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='target',
            table='target',
        ),
    ]
