# Generated by Django 3.1.5 on 2021-12-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0008_alter_target_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='target',
            old_name='database_type',
            new_name='sub_type',
        ),
        migrations.AddField(
            model_name='checklist',
            name='target_sub_type',
            field=models.TextField(blank=True),
        ),
        migrations.AlterModelTable(
            name='target',
            table='targets',
        ),
    ]
