# Generated by Django 3.1.5 on 2021-12-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0009_auto_20211207_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklist',
            old_name='target_sub_type',
            new_name='sub_type',
        ),
    ]
