# Generated by Django 3.1.5 on 2021-12-08 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0010_auto_20211207_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='check_command',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='check_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='frequency',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='handler',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='result_column',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='sub_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='vendor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='archivelog_mode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='blocksize',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='clustered',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='container',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='db_created_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='decommissioned',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='highlysensitiveinfo',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='home_dir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='host_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='hostname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='target',
            name='important_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='instance_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='inventory_create',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='last_check_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='os',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='role',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='serial_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='standby_dest',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='sub_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='support_tier',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='target_type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='v_instance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='vendor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
