# Generated by Django 3.1.5 on 2021-12-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0011_auto_20211207_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='priority',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='blocksize',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='target',
            name='port',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
