# Generated by Django 3.1.5 on 2022-02-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0012_auto_20211207_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('threshold', models.TextField(blank=True, null=True)),
                ('result_column', models.TextField()),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
