# Generated by Django 3.1.5 on 2022-03-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0013_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='enabled',
            field=models.TextField(default='Y', null=True),
        ),
    ]
