# Generated by Django 3.1.5 on 2022-03-11 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codifyweb', '0014_checklist_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='frequency',
            field=models.TextField(default='HOURLY'),
        ),
    ]
